### ISSUE TITLE
로그인 / 회원가입 딜레이 문제

### ISSUE THREAD

**Issue by ahnytae** [ahnytae/bbt-front#1]
데이터처리는 정상이지만
한템포씩 늦게 alert 처리가 됩니다.
refetch 의심이 됩니다

**Comment by jeonbg** [comment]
Alert, Console.log의 렌더링 시점이 달라서 다른 결과값 출력으로 확인

**Comment by jeonbg** [comment]
> 데이터처리는 정상이지만
> 한템포씩 늦게 alert 처리가 됩니다.
> refetch 의심이 됩니다

Alert, Console.log의 렌더링 시점이 달라서 다른 결과값 출력으로 확인

**Comment by ahnytae** [comment]
해결완료 
@jeonbg 감사합니다
